### ISSUE TITLE
NoSuchFileException

### ISSUE THREAD

**Issue by darkcorvushhh** [cansyl/ECPred#12]
I just simply  run "java -jar ECPred.jar weighted sample.fasta /home/user/dyrong/programs/Proteins/ECPred temp/ results.tsv" but got :
Exception in thread "main" java.nio.file.NoSuchFileException: /home/user/dyrong/programs/Proteins/ECPredlib/EC/1.-.-.-/spmap/profile.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:156)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2839)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3330)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3370)
        at seq2vectPSSMtest.calculateVectors(seq2vectPSSMtest.java:115)
        at predictBatchSPMAP.main(predictBatchSPMAP.java:44)
        at runEC.predictions(runEC.java:43)
        at ECPred.main(ECPred.java:108)

And I redownload the repo, got another NoSuchFileException:
Main classes of input proteins are being predicted ... Exception in thread "main" java.nio.file.NoSuchFileException: temp/testResult/1714451370177/1.-.-.-/blast/blast.out at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) at java.base/java.nio.file.Files.newByteChannel(Files.java:371) at java.base/java.nio.file.Files.newByteChannel(Files.java:422) at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) at java.base/java.nio.file.Files.newInputStream(Files.java:156) at java.base/java.nio.file.Files.newBufferedReader(Files.java:2839) at java.base/java.nio.file.Files.readAllLines(Files.java:3330) at java.base/java.nio.file.Files.readAllLines(Files.java:3370) at predictBatchBLAST.main(predictBatchBLAST.java:126) at runEC.predictions(runEC.java:46) at ECPred.main(ECPred.java:108)

How can I solve these issues?

**Comment by emilpaulitz** [comment]
I have a similar problem. This is on a high-performance cluster, in a slurm batch job. The program does not find the output of BLAST, because BLAST does not run (without an error message) because it does not find libidn11. I could not get around this by installing libidn11 so far.

On another node, where libidn11 is installed, the error turns into
```
Exception in thread "main" java.io.FileNotFoundException: [TMP_DIR_INPUT]/testResult/1729767203236/1.-.-.-/pepstats/temp.out (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at fasta2Pepstats_noscale.parse_pepstats(fasta2Pepstats_noscale.java:66)
	at predictBatchPEPSTATS.main(predictBatchPEPSTATS.java:68)
	at runEC.predictions(runEC.java:49)
	at ECPred.main(ECPred.java:108)
```

which is because emboss' pepstats cannot run (again, without printing an error message). Adding an option for users to provide their own (up-to-date) versions of the tools, possibly via a conda environment, would solve all of these problems.

**Comment by emilpaulitz** [comment]
A (very whacky) workaround that solved the problem for me, it to install blast/emboss/... by yourself, e.g. via conda, to make sure it works. Then replace the executable shipped with ECPred with a link to the executable in your conda environment. This tricks the program to execute your (working) version of the tool.

**Comment by emilpaulitz** [comment]
However, this led to an
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at runEC.predictions(runEC.java:110)
        at ECPred.main(ECPred.java:108)
```
after two days of computing, maybe because BLAST did not produce an expected output... Any help would be appreciated!

**Comment by alperendalkiran** [comment]
Hello, thank you for using our tool. Have you tried running ECPred on local Ubuntu or Mac before running on a high-performance cluster? It should work on the local operating system if you have installed the necessary dependencies.

Additionally, have you checked [this thread](https://github.com/cansyl/ECPred/issues/9#issuecomment-1599183855)? A couple of people had a similar problem and that solution worked for them.
