### ISSUE TITLE
File not found error /lib/subclasses/Level2.txt

### ISSUE THREAD

**Issue by babu2749** [cansyl/ECPred#2]
We are getting the following error:
Exception in thread "main" java.io.FileNotFoundException: ./lib/subclasses/Level2.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at ecpred.ECPpred.main(ECPpred.java:123) 
When we compile the ECPred source code and execute. 

Kindly suggest.

**Comment by alperendalkiran** [comment]
Thank you for the notice. We've updated the ECPred website and the links. Could you please redownload ECPred.tar.gz from the website and run it again?
