### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by irazoquimatias** [cansyl/ECPred#3]
Hi,
I've trying to run ECPred today, but I keep getting errors like this one. I don't have much background in JAVA, so I don't know if has to do with my system configuration or with the script itself.

Exception in thread "main" java.lang.NumberFormatException: For input string: "0,84"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at runEC.predictions(runEC.java:148)
        at ECPpred.main(ECPpred.java:109)

I've been trying to run it with the sample fasta and with all 4 methods available, but I always get a similar error.
Thanks in advance!

**Comment by alperendalkiran** [comment]
Hi, Thank you for using our tool. The problem is probably related to your input file. Would it be possible for you to share your input sequence file and your running script? After that, I can gladly provide help. Thank you.

**Comment by irazoquimatias** [comment]
Hi, thanks for answering. I tried to run ECPred with the sample file that comes in the ECPred tar, the one with 3 sequences. I've run it like this:
`$ java -jar ECPred.jar weighted sample.fasta /home/matias/Documents/ECPred test sample.out`
And get the following error:
> Exception in thread "main" java.lang.NumberFormatException: For input string: "0,03"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at runEC.predictions(runEC.java:148)
        at ECPpred.main(ECPpred.java:109)
It happens with every method, it only changes the "input string"

**Comment by alperendalkiran** [comment]
We believe that we have identified the problem and we are working on it at the moment, please stay put until our package update.

**Comment by alperendalkiran** [comment]
We believe that the problem has been solved. Could you please delete all the existing files and redownload ECpred.tar.gz again? You can re-install it from the following link: https://goo.gl/g2tMJ4

**Comment by irazoquimatias** [comment]
Thank you for the reply! I've re-installed ECPred using that link and when I run it using the blast method and it worked perfectly. But when I tried to run it using the weighted method I got this error:
`java -jar ECPred.jar weighted sample.fasta /media/2tb_Nuevo/DBs/ECPred/ test sample.out`
>  Main classes of input proteins are being predicted ...
Exception in thread "main" java.io.FileNotFoundException: test/testResult/1550574080788/1.-.-.-/pepstats/temp.out (No existe el fichero o el directorio)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at fasta2Pepstats_noscale.parse_pepstats(fasta2Pepstats_noscale.java:66)
        at predictBatchPEPSTATS.main(predictBatchPEPSTATS.java:68)
        at runEC.predictions(runEC.java:49)
        at ECPred.main(ECPred.java:108)

I haven't tried the other two methods, since BLAST worked.

**Comment by alperendalkiran** [comment]
We think the problem is related to the EMBOSS tool, in order to solve the problem you need to run the following commands from the terminal. 
cd ECPred
cd lib
cd EMBOSS-6.5.7 
./configure --without-x
make

**Comment by irazoquimatias** [comment]
It worked, thanks!!
