### ISSUE TITLE
fails to run

### ISSUE THREAD

**Issue by splaisan** [cansyl/ECPred#5]
HI!
something is off with my fresh install
I just installed with the latest java on this server, could java 11 be the source of the error?

```
/opt/biotools/ECPred$ java --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)
```

so far so good

```
/opt/biotools/ECPred$ java -jar /opt/biotools/ECPred/ECPred.jar weighted
Missing Argument(s)!
Sample run: java -jar ECPred.jar method inputFile libraryDir tempDir outputFile
method argument can be one of the followings: blast, spmap, pepstats, weighted
outputFile is optinal. If you don't specify the output file name the results will be printed to standard output.

```

all files are here

```
/opt/biotools/ECPred$ ls -lah
total 116K
drwxr-xr-x  3 u0002316 domain users 4.0K Feb 18  2019 .
drwxr-xr-x 54 u0002316 domain users 4.0K May 10 15:05 ..
-rw-r--r--  1 u0002316 domain users 7.4K Nov 26  2017 ECNumberList.txt
-rw-r--r--  1 u0002316 domain users  33K Feb 18  2019 ECPred.jar
-rw-r--r--  1 u0002316 domain users  34K Feb 18  2019 ECPred_woH.jar
drwxr-xr-x  8 u0002316 domain users 4.0K May 10 15:12 lib
-rw-r--r--  1 u0002316 domain users 2.3K Jan  3  2019 README
-rw-r--r--  1 u0002316 domain users 2.3K Jan  3  2019 README_woH
-rw-r--r--  1 u0002316 domain users  108 Jul 12  2018 results.tsv
-rwxr-xr-x  1 u0002316 domain users  279 Nov 28  2017 runLinux.sh
-rwxr-xr-x  1 u0002316 domain users  279 Nov 28  2017 runMac.sh
-rwxr-xr-x  1 u0002316 domain users 1.1K Nov 28  2017 sample.fasta
```

but this fails

```
/opt/biotools/ECPred$ java -jar ./ECPred.jar weighted sample.fasta /opt/biotools/ECPred /tmp out
Main classes of input proteins are being predicted ...
Exception in thread "main" java.nio.file.NoSuchFileException: /opt/biotools/ECPredlib/EC/1.-.-.-/spmap/profile.txt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:156)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2839)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3330)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3370)
        at seq2vectPSSMtest.calculateVectors(seq2vectPSSMtest.java:115)
        at predictBatchSPMAP.main(predictBatchSPMAP.java:44)
        at runEC.predictions(runEC.java:43)
        at ECPred.main(ECPred.java:108)
```

adding /lib to the library location does not help

I noticed this in the stderr text above which is wrong: /opt/biotools/ECPredlib/EC/1

thanks for your help

**Comment by splaisan** [comment]
corrected by adding an alias in /opt/biotools to correct the incorrect path observed in the stderr message
`/opt/biotools$ ln -s ECPred/lib ECPredlib`

**Comment by splaisan** [comment]
OK, now I found it, the path to the library folder lib should be passed with a final '/' after /opt/biotools/ECPred
maybe wise to add this point to the doc

`/opt/biotools/ECPred$ java -jar ./ECPred.jar weighted sample.fasta /opt/biotools/ECPred/ /tmp out`
