### ISSUE TITLE
predictBatchPEPSTATS - no such file

### ISSUE THREAD

**Issue by rpkarandev** [cansyl/ECPred#7]
Greetings,

It would be great if you can help me figure out this error. I am trying to run ECPred on a bunch of sequences. However, I could not get it to run even for the sample fast file.

Main classes of input proteins are being predicted ...
Exception in thread "main" java.io.FileNotFoundException: ./temp/testResult/1673274969648/1.-.-.-/pepstats/temp.out (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at fasta2Pepstats_noscale.parse_pepstats(fasta2Pepstats_noscale.java:66)
        at predictBatchPEPSTATS.main(predictBatchPEPSTATS.java:68)
        at runEC.predictions(runEC.java:49)
        at ECPred.main(ECPred.java:108)

**Comment by alperendalkiran** [comment]
Hello, 
Probably, the EMBOSS Pepstats tool is not working. Could you please share your run command with me?

**Comment by rpkarandev** [comment]
Thank you for the quick response. This is the command I used. I tried varying the temp folder (with/without '/' ). 

java -jar ECPred.jar weighted ./sample.fasta ./ ./temp/ result_sample.tsv

**Comment by rpkarandev** [comment]
Reinstalling libgd lib and ECpred solved the issue.

**Comment by rpkarandev** [comment]
Reinstalling libgd lib and ECpred solved the issue.
