### ISSUE TITLE
predictBatchBLAST does not work

### ISSUE THREAD

**Issue by dsaeedeh** [cansyl/ECPred#8]
Hi,
I got the following error when I ran the model:

Exception in thread "main" java.nio.file.NoSuchFileException: ECPred/temp/testResult/1687194447460/1.-.-.-/blast/blast.out
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:156)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2839)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3330)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3370)
        at predictBatchBLAST.main(predictBatchBLAST.java:126)
        at runEC.predictions(runEC.java:46)
        at ECPred.main(ECPred.java:108)

I'd appreciate it if you could help me to resolve the issue.

**Comment by alperendalkiran** [comment]
It may be possible that the Blast tool was not successfully installed, resulting in the inability to generate the Blast output.
Did you get any errors during the Blast installation? If not, I suggest reinstalling all the tools from the beginning and verifying if any errors occur during the installation process.

**Comment by dsaeedeh** [comment]
Thank you for your reply. I think Blast is installed without any errors. I reinstalled the model several times but still, I received the same error. In directory lib/EC/1.-.-.-/blast, I have the following files: 
ppreds.txt
npreds.txt
1.blastdb.psq
1.blastdb.pin
1.blastdb.phr
1.-.-.-.blastdb.psq
1.-.-.-.blastdb.pin
1.-.-.-.blastdb.phr

Methods spmap and pepstats are working but weighted and blast are not.

**Comment by alperendalkiran** [comment]
That is interesting; it may also be related to the input sequence. Have you been able to try with the sample.fasta file that we provided?  If you're using a different Fasta file, could you please share a few sequences with me?
Additionally, it would be helpful to know which operating system you're currently using.

**Comment by dsaeedeh** [comment]
I used the sample.fasta file you provided with the code. My OS is Ubuntu 22.04.2 LTS.

**Comment by dsaeedeh** [comment]
Solution is here: https://github.com/cansyl/ECPred/issues/9#issuecomment-1599183855
